# Generated by Django 4.2.7 on 2023-12-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('history', models.TextField()),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.dentist')),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField()),
                ('history', models.TextField()),
                ('scheduled', models.TextField()),
                ('note', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tooth',
            constraint=models.CheckConstraint(check=models.Q(('tooth_number__gte', 1), ('tooth_number__lte', 32)), name='tooth_number'),
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together={('patient_id', 'tooth_number')},
        ),
    ]
