# Generated by Django 4.2.7 on 2023-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_patient_gender_patient_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooth',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
